services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=0991553333
      - MYSQL_DATABASE=Finance
      - MYSQL_USER=mouaid_admin
      - MYSQL_PASSWORD=0991553333
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3333:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  flask_app:
    image: mouaidnasab/sharetopi:0
    container_name: flask_container
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=Finance
      - DATABASE_USER=mouaid_admin
      - DATABASE_PASSWORD=0991553333
    working_dir: /usr/src/app
    ports:
      - "4500:4500"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  finance_mysql_data:
    external: true
